### ISSUE TITLE
Question about the results.

### ISSUE THREAD

**Issue by Colmar-zlicheng** [OpenRobotLab/UniHSI#8]
Hi, thanks for your excellent work.

I have tried the code (simple task on partnet), and get the results below. I want to ask does these results in line with the expectations of the paper? I just want to make sure everything I do is correct. Thank you!

https://github.com/OpenRobotLab/UniHSI/assets/111580763/78267da8-9b4c-4c80-9354-4314ebc06b91

![WechatIMG647](https://github.com/OpenRobotLab/UniHSI/assets/111580763/c1ce01d3-33c0-4b8d-983f-ca78c861171a)

https://github.com/OpenRobotLab/UniHSI/assets/111580763/c97755e1-87b5-4cfb-8be3-0308593e5a37

**Comment by xizaoqu** [comment]
Hi, yes it is correct. If you want to remove this, just comment lines in the `_draw_task` function.

**Comment by yhr0710** [comment]
Hi, guys，I would like to know where the output MP4 files are saved after running demo_scannet.sh, and whether it is necessary to specify a location? Thank you!

**Comment by yhr0710** [comment]
> Hi, thanks for your excellent work.
> 
> I have tried the code (simple task on partnet), and get the results below. I want to ask does these results in line with the expectations of the paper? I just want to make sure everything I do is correct. Thank you!
> 
>  demo1.mp4 
> ![WechatIMG647](https://private-user-images.githubusercontent.com/111580763/335948598-c1ce01d3-33c0-4b8d-983f-ca78c861171a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2MzkzODMsIm5iZiI6MTczMDYzOTA4MywicGF0aCI6Ii8xMTE1ODA3NjMvMzM1OTQ4NTk4LWMxY2UwMWQzLTMzYzAtNGI4ZC05ODNmLWNhNzhjODYxMTcxYS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwM1QxMzA0NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMzkwZDgzYzc4OWY1ODJmMzE3NjcxMTI5NGMxZGEzNDljNDg4ODBlYWQ0ZGI3NDZkNjM2ZjA0NTM0NDZjNjA2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.uWUQsbyl0fB37ic_SitllnOMPh4nLtUw7QFPVBv8eOE)
> 
>  demo2.mov
Hi, guys，I would like to know where the output MP4 files are saved after running demo_scannet.sh, and whether it is necessary to specify a location? Thank you!

**Comment by xizaoqu** [comment]
Oh, I just find that I've misunderstood your questions. The results you provided are a little bit weird. Maybe this is because of the batch size error from the early version of my release. You can run the newest version for training and evaluate the given checkpoints for reference.

**Comment by xizaoqu** [comment]
> > Hi, guys，I would like to know where the output MP4 files are saved after running demo_scannet.sh, and whether it is necessary to specify a location? Thank you!

Hi, it will not be automatically saved. I normally use screenshot apps to save it or use the blender for better rendering results.

**Comment by yhr0710** [comment]
> > > Hi, guys，I would like to know where the output MP4 files are saved after running demo_scannet.sh, and whether it is necessary to specify a location? Thank you!
> 
> Hi, it will not be automatically saved. I normally use screenshot apps to save it or use the blender for better rendering results.
Thank you for your prompt response. What I would like to know is, what kind of file will be generated after running the 'sh demo_scannet.sh' command? And then how can I use this file with Blender to render? Thank you!

**Comment by xizaoqu** [comment]
>  Thank you for your prompt response. What I would like to know is, what kind of file will be generated after running the 'sh demo_scannet.sh' command? And then how can I use this file with Blender to render? Thank you!

It will not generate results but prompt a window to show the results by default. So it is recommended to use a local device for visualization. If you want to render it with Blender, please refer to https://github.com/xizaoqu/blender_for_UniHSI.

**Comment by yhr0710** [comment]
> > Thank you for your prompt response. What I would like to know is, what kind of file will be generated after running the 'sh demo_scannet.sh' command? And then how can I use this file with Blender to render? Thank you!
> 
> It will not generate results but prompt a window to show the results by default. So it is recommended to use a local device for visualization. If you want to render it with Blender, please refer to https://github.com/xizaoqu/blender_for_UniHSI.

Hi，Thank you very much for once again supplementing the code and responding promptly. I would like to ask if the Precision metric in the output test_log is equivalent to the Contact Error metric in the paper. Thank you again!

**Comment by xizaoqu** [comment]
> Hi，Thank you very much for once again supplementing the code and responding promptly. I would like to ask if the Precision metric in the output test_log is equivalent to the Contact Error metric in the paper. Thank you again!

Ah yes. Thanks for pointing out. I've fixed the inconsistency.

**Comment by yhr0710** [comment]
> > Hi，Thank you very much for once again supplementing the code and responding promptly. I would like to ask if the Precision metric in the output test_log is equivalent to the Contact Error metric in the paper. Thank you again!
> 
> Ah yes. Thanks for pointing out. I've fixed the inconsistency.

Hello, thank you again for your prompt response. When I am training the hard task using an RTX 4090 GPU, after loading the weights for the mid task, the GPU memory always overflows. Even when I significantly reduce the parameters such as batch_size and amp_batch_size to 2, the issue persists. I am wondering what could be causing this situation? Since the deep networks for all three stages are exactly the same, the first two stages did not encounter such problems, I am quite puzzled. If you have any insights on how to resolve this, I would be very grateful.
